name: Auto-Redeploy Render Every 12 Minutes

on:
    schedule:
      - cron: "*/12 * * * *"
    push:
      branches:
        - stable

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Backend Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_BACKEND_ID }}" \
          -H "Accept: application/json"

      - name: Trigger Render Frontend Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_FRONTEND_ID }}" \
          -H "Accept: application/json"
